### ISSUE TITLE
Remote hungs up unexpectaedly while pushing to azure master

### ISSUE THREAD

**Issue by frrahat** [ilkarman/Azure-WebApp-w-CNTK#1]
Following your step by step instruction, I have,
1. Cloned your repo 
2. Created an web app using azure portal with web browser
3. Scaled up service plan to S1
4. Added python 3.5.3 x64 
5. Set 'Always On' to On
6. Tried to push to azure master using git bash.
And then the following message had been displayed:

`$ git push azure master
Counting objects: 25, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (19/19), done.
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054
fatal: The remoteWriting object end hung up unexpectedly
Writing objects: 100% (25/25), 59.78 MiB | 6.00 KiB/s, done.
Total 25 (delta 0), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
Everything up-to-date`

From Log-Stream of azure portal I got the following:
`Connecting...
2017-04-08T12:02:48  Welcome, you are now connected to log-streaming service.
2017-04-08 12:02:36 CNTKWEBAPPFRRAHAT GET / X-ARR-LOG-ID=edcf5ee8-1a92-4787-b4ec-4ec57ef13be1 80 - 13.85.72.129 AlwaysOn ARRAffinity=f48a766e7a568de51e4d0599762c3f8516fe1cb9a63fdeab6282af05db2ec8ed - cntkwebappfrrahat.azurewebsites.net 200 0 0 67469 670 126
2017-04-08 12:02:44 ~1CNTKWEBAPPFRRAHAT GET / - 80 - 100.114.220.57 AlwaysOn - - cntkwebappfrrahat.azurewebsites.net 200 0 0 2943 473 8931
2017-04-08 12:02:46 CNTKWEBAPPFRRAHAT GET / X-ARR-LOG-ID=525f409c-bb3e-471a-9d0b-293f7b535e1f 80 - 13.85.72.129 AlwaysOn ARRAffinity=f48a766e7a568de51e4d0599762c3f8516fe1cb9a63fdeab6282af05db2ec8ed - cntkwebappfrrahat.azurewebsites.net 200 0 0 67469 670 20
2017-04-08 12:02:46 ~1CNTKWEBAPPFRRAHAT GET / - 80 - 100.114.220.57 AlwaysOn - - cntkwebappfrrahat.azurewebsites.net 200 0 0 2943 473 36
2017-04-08 12:02:46 ~1CNTKWEBAPPFRRAHAT GET /cntkwebappfrrahat.git/info/refs service=git-receive-pack&X-ARR-LOG-ID=cbbedd3f-95dc-47ca-91b7-f0bb1e6c8bbd 443 - 103.58.74.138 git/2.12.0.windows.1 - - cntkwebappfrrahat.scm.azurewebsites.net 200 0 0 763 1021 1418
2017-04-08 12:02:53 ~1CNTKWEBAPPFRRAHAT POST /cntkwebappfrrahat.git/git-receive-pack X-ARR-LOG-ID=b6e4a0c4-0cdf-4054-9a9f-5c892c5747af 443 - 103.58.74.138 git/2.12.0.windows.1 - - cntkwebappfrrahat.scm.azurewebsites.net 200 0 0 507 1705 2211
2017-04-08T12:04:48  No new trace in the past 1 min(s).
2017-04-08T12:05:05    Outgoing response, type: response, statusCode: 500, statusText: Internal Server Error, Server: Microsoft-IIS/8.0
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS Detailed Error - 500.0 - Internal Server Error</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.0 - Internal Server Error</h3> 
<h4>Internal Server Error</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;ManagedPipelineHandler</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;Kudu.Services.GitServer.ReceivePackHandler</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x800703e3</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://~1cntkwebappfrrahat:80/cntkwebappfrrahat.git/git-receive-pack</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\Program Files (x86)\SiteExtensions\Kudu\61.60316.2745\cntkwebappfrrahat.git\git-receive-pack</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x800703e3,9200">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p> 
  
 
</fieldset> 
</div> 
</div> 
</body> 
</html> 
2017-04-08T12:05:50    Outgoing response, type: response, statusCode: 500, statusText: Internal Server Error, Server: Microsoft-IIS/8.0
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS Detailed Error - 500.0 - Internal Server Error</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.0 - Internal Server Error</h3> 
<h4>Internal Server Error</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;ManagedPipelineHandler</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;Kudu.Services.GitServer.ReceivePackHandler</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x800703e3</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://~1cntkwebappfrrahat:80/cntkwebappfrrahat.git/git-receive-pack</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\Program Files (x86)\SiteExtensions\Kudu\61.60316.2745\cntkwebappfrrahat.git\git-receive-pack</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x800703e3,9200">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p> 
  
 
</fieldset> 
</div> 
</div> 
</body> 
</html> 
2017-04-08T12:07:48  No new trace in the past 1 min(s).
2017-04-08 12:07:49 ~1CNTKWEBAPPFRRAHAT GET / - 80 - 100.114.220.57 AlwaysOn - - cntkwebappfrrahat.azurewebsites.net 200 0 0 2946 473 5
2017-04-08 12:07:49 CNTKWEBAPPFRRAHAT GET / X-ARR-LOG-ID=e0513dc5-c4dd-41f5-b371-4569e19a87b4 80 - 13.85.72.129 AlwaysOn ARRAffinity=f48a766e7a568de51e4d0599762c3f8516fe1cb9a63fdeab6282af05db2ec8ed - cntkwebappfrrahat.azurewebsites.net 200 0 0 67469 670 8
2017-04-08T12:09:48  No new trace in the past 1 min(s).
2017-04-08T12:10:48  No new trace in the past 2 min(s).
2017-04-08T12:11:48  No new trace in the past 3 min(s).
2017-04-08T12:12:39
System.ApplicationException: The trace listener AzureBlobTraceListener is disabled. ---> System.InvalidOperationException: The SAS URL for the cloud storage account is not specified. Use the environment variable 'DIAGNOSTICS_AZUREBLOBCONTAINERSASURL' to define it.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.RefreshConfig()
   --- End of inner exception stack trace ---

2017-04-08 12:12:50 ~1CNTKWEBAPPFRRAHAT GET / - 80 - 100.114.220.57 AlwaysOn - - cntkwebappfrrahat.azurewebsites.net 200 0 0 2946 473 15
2017-04-08 12:12:50 CNTKWEBAPPFRRAHAT GET / X-ARR-LOG-ID=812ade4d-e3c1-4974-974b-1aa9211aa704 80 - 13.85.72.129 AlwaysOn ARRAffinity=f48a766e7a568de51e4d0599762c3f8516fe1cb9a63fdeab6282af05db2ec8ed - cntkwebappfrrahat.azurewebsites.net 200 0 0 67469 670 15`

**Did I miss anything?**

**Comment by ilkarman** [comment]
In your main folder if you navigate to the hidden '.git' folder and then open config do you something like this:
```
[remote "azure"]
	url = https://<your_username>@<app_name>.scm.azurewebsites.net/<app-name>.git
	fetch = +refs/heads/*:refs/remotes/azure/*
```

I haven't seen that error before, however if it's not related to [this](http://stackoverflow.com/questions/12790215/git-push-to-azure-failing-rpc-failed/39294072#39294072) and you are on Windows I could try and replicate it? 

Alternatively, I have updated the install instructions now to use the latest azure-cli (v2.0) commands, which may iron out some issues. My versions are:
```
az --version  # time-of-writing: 2.0.1
git --version # time of writing: 2.9.2.windows.1
```

**Comment by frrahat** [comment]
I have figured out that this error is not related to this repository as I have succeeded in deployment with different pc with different internet connections following the same steps. Thank you.
